version: '3'

services:
  postgres:
    container_name: rwanda_postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    container_name: rwanda_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - pgadmin4
      - redis
      - worker

  pgadmin4:
    container_name: rwanda_pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgre@rwanda.com
      - PGADMIN_DEFAULT_PASSWORD=togorwanda
    ports:
      - 5050:80

  redis:
    container_name: rwanda_redis
    image: library/redis:6.0-alpine
    restart: unless-stopped

  worker:
    build: .
    container_name: rwanda_worker
    command: celery -A rwanda worker --loglevel=info
    volumes:
      - ./:/code
    depends_on:
      - redis
      - postgres
    restart: unless-stopped