version: '3'

services:
  rwanda:
    container_name: rwanda
    build: .
    command: gunicorn rwanda.asgi -w 4 --threads 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --preload --timeout 60 --graceful-timeout 60
    volumes:
      - .:/code
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.rwanda.rule=Host(`rwanda.mdtaf.com`,`www.rwanda.mdtaf.com`)
      - traefik.http.routers.rwanda.tls=true
      - traefik.http.routers.rwanda.tls.certresolver=le
      - traefik.port=8000
      - traefik.docker.network=traefik-proxy
      networks:
        - default
        - traefik-proxy
    depends_on:
      - rwanda_postgres
      - rwanda_pgadmin4
      - rwanda_redis
      - rwanda_worker
      - rwanda_scheduler
    restart: unless-stopped

  rwanda_postgres:
    container_name: rwanda_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - rwanda_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  rwanda_pgadmin4:
    container_name: rwanda_pgadmin4
    image: dpage/pgadmin4:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.rwanda_pgadmin4.rule=Host(`pgadmin.mdtaf.com`)
      - traefik.http.routers.rwanda_pgadmin4.tls=true
      - traefik.http.routers.rwanda_pgadmin4.tls.certresolver=le
      - traefik.port=80
      - traefik.docker.network=traefik-proxy
      networks:
        - default
        - traefik-proxy
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - rwanda_postgres
    restart: unless-stopped

  rwanda_redis:
    container_name: rwanda_redis
    image: redis:alpine
    volumes:
      - rwanda_redis:/data
    restart: unless-stopped

  rwanda_worker:
    build: .
    container_name: rwanda_worker
    command: celery -A rwanda worker -l INFO --concurrency=2 --autoscale=2,1 --time-limit=3600
    volumes:
      - ./:/code
    depends_on:
      - rwanda_redis
      - rwanda_postgres
    restart: unless-stopped

  rwanda_scheduler:
    build: .
    container_name: rwanda_scheduler
    command: celery -A rwanda beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/code
    depends_on:
      - rwanda_redis
      - rwanda_postgres
    restart: unless-stopped

volumes:
  rwanda_postgres:
  rwanda_redis:

networks:
  default:
    name: rwanda_network

  traefik-proxy:
    external: true